# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-21 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgpi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greet',
            old_name='gret',
            new_name='grett',
        ),
    ]
