# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-04 09:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgpi', '0002_auto_20180821_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=500)),
                ('Item_no', models.CharField(max_length=100)),
                ('Customer_name', models.CharField(max_length=500)),
                ('Distr_name', models.CharField(max_length=500)),
                ('Order_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cust_name', models.CharField(max_length=500)),
                ('Pro_id', models.CharField(max_length=500)),
                ('Pay_amt', models.IntegerField(default=10000)),
                ('pay_id', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='greet',
            old_name='grett',
            new_name='greets',
        ),
    ]
