# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-04 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgpi', '0004_auto_20180904_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='B_y_e',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bye', models.CharField(max_length=100)),
            ],
        ),
    ]
