# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-07 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgpi', '0006_auto_20180907_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='b_y_e',
            old_name='rsp',
            new_name='bye',
        ),
    ]
