# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-07 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgpi', '0007_auto_20180907_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='Cust_name',
            new_name='custo_name',
        ),
        migrations.AddField(
            model_name='purchase',
            name='pro_query',
            field=models.CharField(default='buy jewellery', max_length=500),
        ),
    ]
