# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-10 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgpi', '0008_auto_20180907_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='resp',
            name='tag',
            field=models.CharField(default='greet', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='pro_query',
            field=models.CharField(max_length=500),
        ),
    ]
