# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-10 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgpi', '0009_auto_20180910_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resp',
            name='tag',
            field=models.CharField(max_length=100),
        ),
    ]
